# Generated by Django 5.0.6 on 2024-05-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saborexpressapp', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
