# Generated by Django 5.0.6 on 2024-05-29 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saborexpressapp', '0003_alter_recipe_image_url_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='saborexpressapp.user'),
        ),
    ]
